#!/bin/sh

# Generate ssh keys if not exist
if [ "$(ls /etc/ssh/ssh_host_* 1>/dev/null 2>&1)" ]; then
	echo "found existing hostkey(s)"
else
	echo "creating new hostkeys..."
	yes n | ssh-keygen -q -N "" -t ed25519 -f /etc/ssh/ssh_host_ed25519_key
	yes n | ssh-keygen -q -N "" -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key
fi

# Add public keys to authorized keys
if [ "$(ls -A /keys/)" ]; then
	echo "adding keys..."
	cd /home/git
	cat /keys/* > .ssh/authorized_keys
	chown -R git:git .ssh
	chmod 700 .ssh
	chmod -R 600 .ssh/*
fi

# Checking permissions and fixing SGID bit in repos folder
# More info: https://github.com/jkarlosb/git-server-docker/issues/1
if [ "$(ls -A /repos/)" ]; then
	echo "adding repos..."
	cd /repos
	chown -R git:git .
	chmod -R ug+rwX .
	find . -type d -exec chmod g+s '{}' +
fi

echo "starting sshd..."

# -D flag avoids executing sshd as a daemon
/usr/sbin/sshd -D
